name: 도커 이미지를 빌드하고 ECS에 푸시하자.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: package.json에서 어플리케이션 버전 가져오기
        id: package_version
        run: echo "::set-output name=VERSION::$(cat package.json | jq -r .version)"

      - name: AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Amazon ECR에 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker 이미지 빌드 및 푸시
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          IMAGE_TAG: ${{ steps.package_version.outputs.VERSION }}
        run: |
          # Build your Docker image with the version from package.json.
          docker build -t medipot-back .
          
          # Docker 이미지를 ECR 레지스트리로 푸시
          docker tag medipot-back $ECR_REGISTRY/medipot-back:$IMAGE_TAG
          docker push $ECR_REGISTRY/medipot-back:$IMAGE_TAG

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SSH로 EC2에 접속
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            docker stop medipot-back || true
            docker rm medipot-back || true

            cd medipot-back
            
            # ECR에서 Docker 이미지를 가져오기
            docker pull $ECR_REGISTRY/medipot-back:${{ needs.build-and-push.outputs.IMAGE_TAG }}
            
            # 새로운 Docker 컨테이너 실행
            docker run -d --name medipot-back -p 80:4000 $ECR_REGISTRY/medipot-back:${{ needs.build-and-push.outputs.IMAGE_TAG }}